import React from 'react'
import Head from 'next/head'

const CustomHead = () => {
  return (
    <>
      <Head>
        <title>NiziChain</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/BigMamFavicon.ico' />
      </Head>
    </>
  )
}

export default CustomHead
